name: Python CI

# Trigger this workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:
  test:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Steps to execute in the job
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v3

      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Run the tests using Poetry and pytest or unittest
      - name: Run tests
        run: |
          poetry run pytest
