name: Python CI

# Trigger this workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:
  test:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Test on different Python versions
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    # Steps to execute in the job
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v3

      # Set up Python with the version specified in the matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Run the tests using Poetry and pytest or unittest
      - name: Run tests
        run: |
          poetry run pytest
